server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/heima-estate?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: info
